<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>

    <td class="<?php if ($this->isShipmentRegular()): ?>last<?php endif; ?> a-center">
        <?php if ($this->canShipPartiallyItem()): ?>
            <input type="text" class="input-text" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty() * 1 ?>" />
        <?php else: ?>
            <?php echo $_item->getQty() * 1 ?>
        <?php endif; ?>
    </td>
    <td><?php
        echo $this->getLayout()->createBlock('batchcode/adminhtml_batchcode_productbatches/')->setData('product_id', $_item->getProductId())->setData('qty_ordered', $_item->getQty())->setData('order_item_id', $_item->getOrderItemId())->toHtml();
        ?>



    </td>
    <?php if (!$this->canShipPartiallyItem()): ?>
        <td class="a-center last">
            <input type="hidden" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
            <input type="checkbox" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty() * 1 ?>" checked />
        </td>
    <?php endif; ?>



</tr>
