<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td class="a-center"><?php echo $_item->getQty()*1 ?></td>
    <td><?php  echo $this->getLayout()->createBlock('batchcode/adminhtml_batchcode_batch/')->setData('order_item_id', $_item['order_item_id'])->toHtml();?></td>
</tr>

<?php // echo $_item[order_item_id];
//print_r($_item[order_item_id]);

?>