<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>


<div class="column_h">
    <?php
    $batches = $this->getBatchcode();
    if ($batches) {
        foreach ($batches as $batch) {

            echo $batch->getBatchNumber();
            echo ' [' . date("d-m-Y", strtotime($batch->getExpirationDate())) . ']';

            echo '<br>';
        }
    } else {
        echo 'No batchcodes for this product';
    }
    ?>
</div>